return {
  name = "LCARS",
  style = "dark",
  palette = {
    base = { bg = "#000000", fg = "#CCBBAA" },
    stdout = { fg = "#CCBBAA" },
    comment = { fg = "#554F45", modifiers = { "italic" } },
    punctuation = { fg = "#9988CC" },
    constant = { fg = "#CC8800" },
    constant.numeric = { fg = "#CC8800" },
    constant.character = { fg = "#CC7733" },
    constant.boolean = { fg = "#CC8800" },
    string = { fg = "#66CC99" },
    string.special = { fg = "#99CCFF" },
    variable = { fg = "#CCBBAA" },
    variable.parameter = { fg = "#AA9988" },
    variable.builtin = { fg = "#5588CC" },
    label = { fg = "#9988CC" },
    attribute = { fg = "#CC8899" },
    type = { fg = "#9988CC" },
    type.builtin = { fg = "#BB99EE" },
    constructor = { fg = "#CC7733" },
    function = { fg = "#5588CC" },
    function.builtin = { fg = "#7799DD" },
    function.macro = { fg = "#9988CC" },
    keyword = { fg = "#9988CC" },
    keyword.control = { fg = "#CC8899" },
    operator = { fg = "#CC7733" },
    tag = { fg = "#CC3333" },
    attribute = { fg = "#CC8800" },
    special = { fg = "#99CCFF" },
    diff.plus = { fg = "#66CC99" },
    diff.minus = { fg = "#CC3333" },
    diff.delta = { fg = "#CC8800" },
    ui.statusline = { fg = "#CCBBAA", bg = "#0D0D1E" },
    ui.statusline.normal = { fg = "#1A1020", bg = "#9988CC" },
    ui.statusline.insert = { fg = "#000000", bg = "#66CC99" },
    ui.statusline.select = { fg = "#000000", bg = "#9988CC" },
    ui.cursor = { fg = "#1A1020", bg = "#9988CC" },
    ui.cursor.match = { fg = "#1A1020", bg = "#CC7733" },
    ui.cursor.primary = { fg = "#1A1020", bg = "#9988CC" },
    ui.cursorline.primary = { bg = "#0D0D1E" },
    ui.linenr = { fg = "#3A3550" },
    ui.linenr.selected = { fg = "#9988CC" },
    ui.selection = { bg = "#2A2550" },
    ui.selection.high = { bg = "#352E60" },
    ui.cursorline.secondary = { bg = "#0D0D1E" },
    ui.popup = { bg = "#000000", border = "#9988CC" },
    ui.window = { bg = "#000000" },
    ui.menu = { bg = "#000000", fg = "#CCBBAA" },
    ui.menu.selected = { bg = "#2A2550", fg = "#CCBBAA" },
    ui.menu.scroll = { fg = "#554F45", bg = "#0D0D1E" },
    ui.help = { bg = "#000000", fg = "#CCBBAA" },
    ui.info = { fg = "#5588CC" },
    ui.hint = { fg = "#66CC99" },
    ui.warning = { fg = "#CC8800" },
    ui.error = { fg = "#CC3333" },
    ui.virtual.whitespace = { fg = "#3A3550" },
    ui.virtual.ruler = { bg = "#0D0D1E" },
    ui.virtual.indent = { fg = "#1A1530" },
    ui.bufferline = { fg = "#9988CC", bg = "#0D0D1E" },
    ui.bufferline.active = { fg = "#9988CC", bg = "#000000", modifiers = { "bold" } },
    ui.bufferline.background = { bg = "#000000" },
    markup = { fg = "#CCBBAA" },
    markup.heading = { fg = "#9988CC", modifiers = { "bold" } },
    markup.list = { fg = "#CC7733" },
    markup.bold = { modifiers = { "bold" } },
    markup.italic = { modifiers = { "italic" } },
    markup.link.url = { fg = "#5588CC", modifiers = { "underlined" } },
    markup.link.text = { fg = "#5588CC" },
    markup.raw = { fg = "#99CCFF" },
    markup.raw.block = { fg = "#AA9988" },
    diff = {},
    diff.added = { fg = "#66CC99" },
    diff.removed = { fg = "#CC3333" },
    diff.changed = { fg = "#CC8800" },
    diagnostic = {},
    "diagnostic.hint" = { underline = { style = "curl" } },
    "diagnostic.lsp" = "info",
    "diagnostic.error" = { underline = { style = "curl" }, color-modifiers = { "bold" } },
    "diagnostic.warning" = { underline = { style = "curl" } },
    "diagnostic.info" = { underline = { style = "curl" } },
    "class" = "type",
    "namespace" = "type",
    "variable.other.member" = "variable",
    "variable.other.readonly" = "constant",
    "constant.language" = "constant",
    "string.regexp" = "string.special",
    "punctuation.special" = "string.special",
  },
  highlights = {},
}
